# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5356e5c73a890b2c6469ead7cefe60f665df808b7ff8fed97ef574e7a66b76d21776ecac2aad2106c9aa19443cc9919b282c572c9394aaaa6a117698fa349cc1

test:
  secret_key_base: d88ac5d5f4d955aba5031bc1f5d39da8baa09359f820b3e80525e37764cd590ff07d5190607c1c932dbc45494108570d396095addf47bbdeaf0d91e8659913ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
